// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using om_svc_inventory.Data;

#nullable disable

namespace om_svc_inventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("om_svc_inventory.Models.InventoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19386c96-8197-48fd-b89c-01d52eb5ad73"),
                            Name = "Chair"
                        },
                        new
                        {
                            Id = new Guid("9f6e6232-43e3-4c14-b99d-e5485af44cd9"),
                            Name = "Table"
                        },
                        new
                        {
                            Id = new Guid("7b58054d-2fbb-4b82-a14f-4a7d4ad076db"),
                            Name = "Pole Tent"
                        },
                        new
                        {
                            Id = new Guid("c53eac40-eff4-49bd-a18d-761f50975aae"),
                            Name = "Frame Tent"
                        });
                });

            modelBuilder.Entity("om_svc_inventory.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c7e739f3-9f8d-4d20-992d-8e2c6638e947"),
                            CategoryId = new Guid("19386c96-8197-48fd-b89c-01d52eb5ad73"),
                            Name = "Burgundy Folding",
                            Price = 0.60m
                        },
                        new
                        {
                            Id = new Guid("7081f119-c671-4898-920e-7536248c0753"),
                            CategoryId = new Guid("9f6e6232-43e3-4c14-b99d-e5485af44cd9"),
                            Name = "8' Banguet",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = new Guid("11ff3db8-bce2-4cf0-bfb9-152f3ac70f75"),
                            CategoryId = new Guid("7b58054d-2fbb-4b82-a14f-4a7d4ad076db"),
                            Name = "20 X 30",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = new Guid("4c6fda94-34de-4fc8-889d-49c1b8d778c6"),
                            CategoryId = new Guid("c53eac40-eff4-49bd-a18d-761f50975aae"),
                            Name = "20 X 40",
                            Price = 375.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
